collections_config:
  content:
    path: content
    name: Content
    icon: wysiwyg
  app:
    path: app
    name: App
    icon: photo
  out:
    path: out/index.html
    name: Out
    icon: wysiwyg  
paths:
  static: ''
  uploads: docs/_static
timezone: America/New_York

_editables:
  text:
    bold: true
    italic: true
    underline: true
  block:
    format: p h1 h2 h3 h4 h5
    undo: true
    redo: true
  image:
    mime_type: image/png
    allowed_sources:
      - site-files