_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
data_config:
  homepage:
    path: content/homepage.json
    fields:
      - type: text
        name: title
        label: Title
      - type: textarea
        name: description
        label: Description
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
